### ISSUE TITLE
Runtime configuration

### ISSUE THREAD

**Issue by Emilien-M** [timdeschryver/timdeschryver.dev#104]
Hi Tim,

In this article [angular-build-once-deploy-to-multiple-environments](https://github.com/timdeschryver/timdeschryver.dev/blob/main/content/blog/angular-build-once-deploy-to-multiple-environments/index.md) you describe how to load config at runtime.

In some package module, i need to pass a config through the forRoot method. Do you have an elegant way to populate the forRoot() method with a runtime configuration ?

**Comment by timdeschryver** [comment]
Hey @Emilien-M , we used Injection Tokens to do this.
If you need to pass the config object via the `forRoot()`, I think you could declare a global config variable (probably in a separate file), which is set in the `main.ts` file, and which is imported in the modules.

```
let config;

// used in main.ts
function setConfig(conf) {
  config = conf;
}


// imported in app.module.ts (or another file)
function readConfig() {
  return config;
}
```
