### ISSUE TITLE
Article not loading in Edge

### ISSUE THREAD

**Issue by berthertogen** [timdeschryver/timdeschryver.dev#13]
## Expected Behavior
Article detail is loaded.

## Current Behavior
Article detail is not loaded, getting a error message:

```
500
Cannot convert null or undefined to object
```

And some console errors:

```
0: Cannot convert null or undefined to object
client.cf895b4f.js (1,17176)

0: Object doesn't support property or method 'addEventListener'
client.cf895b4f.js (1,9095)

SCRIPT1028: SCRIPT1028: Expected identifier, string or number
2c2e4caa-c199-466f-9bb2-851db618139a (1,140260)

20: Object doesn't support property or method 'addEventListener'
client.cf895b4f.js (1,9095)
```

## Possible Solution
/

## Steps to Reproduce
1. Op Edge (Microsoft Edge 44.18362.449.0, Microsoft EdgeHTML 18.18362)
2. Navigate to https://timdeschryver.dev/blog/help-angular-to-make-your-application-faster
3.
4.

## Context (Environment)
/

## Detailed Description
/

## Possible Implementation
/

**Comment by timdeschryver** [comment]
Closed by #14
