### ISSUE TITLE
Wow, your blog is awesome!

### ISSUE THREAD

**Issue by alexanderbird** [timdeschryver/timdeschryver.dev#288]
Hi Tim,

I'm reading https://timdeschryver.dev/blog/adding-opentelemetry-to-an-angular-application and am really appreciating all the details you've put into it:
 - highlighting the other related resources, and what niche yours fits in ("While there is already useful content surrounding this topic...", "...how I added OpenTelemetry to an application built with Angular")
 - explaining terms like "span" vs "event" using both the official and the common terms ("A trace represents a collection of events (spans is the correct term)")
 - the `npm install` instructions for following along
 - the beautiful code snippets with the context visible but grayed out
 - the level of detail -- it makes things clear without making it overwhelming

Thanks!!
Alex

**Comment by timdeschryver** [comment]
You just made my day @alexanderbird , thanks for the kind words!
