### ISSUE TITLE
Comments section is broken on blog

### ISSUE THREAD

**Issue by MatthewCaseres** [timdeschryver/timdeschryver.dev#306]
### Discussed in https://github.com/timdeschryver/timdeschryver.dev/discussions/305

<div type='discussions-op-text'>

<sup>Originally posted by **MatthewCaseres** December 29, 2023</sup>
getting 403 forbidden when trying to GET the comments</div>

**Comment by timdeschryver** [comment]
This was a problem on giscus's side, and should be resolved.
Thanks for pointing this out.
