### ISSUE TITLE
'Disable Validators' section of Signal Forms blog post not highlighting fully

### ISSUE THREAD

**Issue by michael-small** [timdeschryver/timdeschryver.dev#316]
In the blog post ["Bringing the power of Signals to Angular Forms with Signal Forms"](https://timdeschryver.dev/blog/bringing-the-power-of-signals-to-angular-forms-with-signal-forms), the ['Disable Validators'](https://timdeschryver.dev/blog/bringing-the-power-of-signals-to-angular-forms-with-signal-forms#disable-validators) code example does not highlight fully. 

I have attached a photo of how it renders on my desktop Chrome (and also Firefox). NOTE: The yellow highlighting of `disable` is my Control + F highlighting. 

I see how you target the lines in the [`index.md`](https://github.com/timdeschryver/timdeschryver.dev/blob/main/blog/bringing-the-power-of-signals-to-angular-forms-with-signal-forms/index.md) for the article, but I don't understand the highlighter enough to suggest a concrete fix.

Great article overall! I enjoy the highlighting by non-blurring aspect of the code blocks. 

![image](https://github.com/timdeschryver/timdeschryver.dev/assets/33669563/f78d258c-73ea-4a20-adca-7d5a6344dd7a)

**Comment by timdeschryver** [comment]
Thanks for  letting me know @michael-small .
This should be resolved, the issue was prettier that formatted the snippets.
