### ISSUE TITLE
How to test svelte components broken due to ongoing issue with svelte-jester

### ISSUE THREAD

**Issue by brianbancroft** [timdeschryver/timdeschryver.dev#55]
Hi there, this is more a heads up than anything. I'm sure if the issue gets fixed that your article will be sound once again. 

Would you be willing to share which versions you used at the time?

https://github.com/mihar-22/svelte-jester/issues/65

This is in reference to the following article: https://github.com/timdeschryver/timdeschryver.dev/blob/main/content/blog/how-to-test-svelte-components/index.md

**Comment by timdeschryver** [comment]
Oh yikes, thanks for the heads up.
I believe it was version ^1.0.3`, the versions are also visible in [this snippet](https://timdeschryver.dev/blog/how-to-test-svelte-components#19995b65a1cca38d2ec75e163c1b18fa)

**Comment by brianbancroft** [comment]
Thanks tim!
