### ISSUE TITLE
css overlay and general padding

### ISSUE THREAD

**Issue by crh225** [timdeschryver/timdeschryver.dev#84]
Hi Tim,
Im using Google Chrome latest version on Windows 10.
I found this article a little difficult to read due to the css. It was much easier to just go to the github markdown file. Some of the css is being overlayed, and there appears to have no padding on the sides. 
![image](https://user-images.githubusercontent.com/19475195/163218823-17088db7-4f96-4384-bb34-9b05952db5db.png)

another blog post about angular directives, it was hard to look at the embedded stack blitz
![image](https://user-images.githubusercontent.com/19475195/163219463-0dd6ecc3-3bc7-4268-b267-acc288bddf11.png)

**Comment by crh225** [comment]
https://www.loom.com/share/64aa41c872014f6ba0e7e78bfab63c9a

**Comment by timdeschryver** [comment]
Oh no, sorry for this experience.
I see that this issue is closed, was this on purpose and is this resolved, or does this still happen @crh225 ?

**Comment by crh225** [comment]
@timdeschryver its still appears this way for me, but I wasnt sure if it was a stylistic choice or something wrong on my end. 😄

**Comment by crh225** [comment]
The article is really good! it helps me think in c# how I already think in angular!

**Comment by crh225** [comment]
hard refresh worked! I forget to do that in debugging things. Actually my own website has a similar service worker issue.

**Comment by timdeschryver** [comment]
Good to know, thanks @crh225 !
