### ISSUE TITLE
Mistake in the post "the-simplicity-of-net-endpoints"

### ISSUE THREAD

**Issue by vancodocton** [timdeschryver/timdeschryver.dev#94]
I've read your blog [The simplicity of ASP.NET Endpoints.](https://github.com/timdeschryver/timdeschryver.dev/blob/main/content/blog/the-simplicity-of-net-endpoints/index.md) It's great but I found a little mistake in your first example about Controller Api, as the following picture.
![image](https://user-images.githubusercontent.com/55989165/174087734-6bb3bfb4-63f7-4d90-afa9-1dd966eadc24.png)

I thinks it's just a copy-and-paste mistake that `command` in `customer.Block(command.Reason);` should be `blockCustomer`.

**Comment by vancodocton** [comment]
I've created the pull request already. Wait for you to approve it.

**Comment by timdeschryver** [comment]
Thanks @vancodocton 🤗
Closed by #95
